USE [Kadr]
GO

/****** Object:  Table [dbo].[Category]    Script Date: 16.05.2014 12:20:35 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[CategoryVPO](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[CategoryVPOName] [varchar](50) NOT NULL,
	[CategoryVPOSmallName] [varchar](50) NOT NULL,
	[OrderBy] [int] NULL
 CONSTRAINT [PK_CategoryVPO] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [IX_CategoryVPO] UNIQUE NONCLUSTERED 
(
	[CategoryVPOName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [IX_Category_1VPO] UNIQUE NONCLUSTERED 
(
	[CategoryVPOSmallName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

GO

CREATE TABLE [dbo].[CategoryZP](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[CategoryZPName] [varchar](50) NOT NULL,
	[CategoryZPSmallName] [varchar](50) NOT NULL,
	[OrderBy] [int] NULL
 CONSTRAINT [PK_CategoryZP] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [IX_CategoryZP] UNIQUE NONCLUSTERED 
(
	[CategoryZPName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [IX_Category_1ZP] UNIQUE NONCLUSTERED 
(
	[CategoryZPSmallName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

